services:
  - type: web
    name: billing-system
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate --show
      php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_KEY
        value: " base64:N3xQAWcMwYXmn2PlSSwZf2gV7P6sKXGKJ6aBYTYG3e4="
      - key: APP_ENV
        value: "production"
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: "http://localhost:8000"
      - key: DB_CONNECTION
        value: "mysql"
      - key: DB_HOST
        value: "127.0.0.1"
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        value: "billingsystem"
      - key: DB_USERNAME
        value: "root"
      - key: DB_PASSWORD
        value: ""
